### ISSUE TITLE
Escaping problem in attribution name field

### ISSUE THREAD

**Issue by tieguy** [tarmot/wp-cc-plugin#27] opened 2014-03-16 01:43 UTC
In the "Attribution work to name:"  field, I typed "Luis Villa's Blog" and hit save; when I went to view the footer, I saw "Luis Villa\'s Blog". When I changed the settings, I ended up with Luis Villa\\'s Blog.

**Comment by BjornW** [comment] 2014-03-16 10:28
@tieguy Thanks! That's a nasty bug. I will look into it and fix it.

**Comment by BjornW** [comment] 2014-03-25 11:49
@tieguy which version of wplicense are you using? I can't find this string  "Attribution work to name:"

**Comment by BjornW** [comment] 2014-04-07 13:38
I'll close this issue for now because I cannot reproduce it & I suspect @tieguy is using a different plugin.

**Closed as completed by BjornW** 2014-04-07 13:38 UTC
Labels: bug
